apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mybank-gateway
  namespace: mybank
spec:
  selector:
    istio: ingressgateway
  servers:
    # HTTPS for all services (*.mybank.com)
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: mybank-tls-cert
      hosts:
        - "*.mybank.com"
        - "mybank.com"
    # HTTP redirect to HTTPS
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*.mybank.com"
        - "mybank.com"
      tls:
        httpsRedirect: true
