apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: mybank
data:
  SPRING_APPLICATION_NAME: "payment-service"
  SERVER_PORT: "8083"

  # MongoDB Configuration
  SPRING_DATA_MONGODB_HOST: "mongodb"
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_DATABASE: "mybank_payment"

  # Logging
  LOGGING_LEVEL_COM_MYBANK_PAYMENT: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_KAFKA: "INFO"
