apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: mybank
data:
  SPRING_APPLICATION_NAME: "user-service"
  SERVER_PORT: "8085"

  # PostgreSQL Configuration
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-user:5432/mybank_user"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"

  # JPA Configuration
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"

  # Logging
  LOGGING_LEVEL_COM_MYBANK_USER: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "INFO"
