apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-service
  namespace: mybank
  labels:
    app: investment-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: investment-service
  template:
    metadata:
      labels:
        app: investment-service
        tier: backend
    spec:
      containers:
        - name: investment-service
          image: mybank/investment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: common-config
            - configMapRef:
                name: investment-service-config
            - secretRef:
                name: common-secret
          env:
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: MONGODB_USERNAME
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: MONGODB_PASSWORD
            - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: MONGODB_AUTH_DATABASE
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 90
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: investment-service
  namespace: mybank
spec:
  type: ClusterIP
  selector:
    app: investment-service
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http
